name: YT 3

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2,8,14 * * *'


jobs:
  capture_screenshots:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        usersname:
          - "usernamesA"
          - "usernamesB"
          - "usernamesC"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
           python-version: '3.10'
           
      - name: Print date and time
        run: echo "Workflow started at $(TZ='Asia/Ho_Chi_Minh' date)"
        
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update and upgrade packages
        run: sudo apt-get update && sudo apt-get upgrade -y
      
      - name: Install dependencies
        run: pip install selenium
      
      - name: Install FFmpeg
        run: sudo apt-get install -y ffmpeg

      - name: Create user folders
        run: mkdir -p $GITHUB_WORKSPACE/${{ matrix.usersname }}

      - name: Run Selenium script
        run: python main4.py -username ${{ matrix.usersname }}
      - name: Archive screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.usersname }}
          path: ${{ matrix.usersname }}

  youtube_bot:
    strategy:
      matrix:
        os: [macos-latest, windows-2019, windows-latest, windows-2019, windows-2022]
        

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
           python-version: '3.10'

      - name: Install dependencies
        run: pip install selenium

      - name: Run Selenium script
        run: python selenium.py

      - name: Archive screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots-${{ matrix.os }}-${{ matrix.python-version }}
          path: .
